import type { Job } from "../types/jobs.types";

import abbLogo from "@/assets/imgs/companies/abb.png";
import sonyLogo from "@/assets/imgs/companies/sony.png";
import lgLogo from "@/assets/imgs/companies/lg.png";
import phillipsLogo from "@/assets/imgs/companies/phillips.png";
import hpLogo from "@/assets/imgs/companies/hp.png";
import samsungLogo from "@/assets/imgs/companies/samsung.png";
import nokiaLogo from "@/assets/imgs/companies/nokia.png";

const companyLogos = {
  abb: abbLogo,
  sony: sonyLogo,
  lg: lgLogo,
  phillips: phillipsLogo,
  hp: hpLogo,
  samsung: samsungLogo,
  nokia: nokiaLogo,
};

export const matchingJobs: Job[] = [
  {
    id: 1,
    title: "Senior Product Designer",
    company: "ABB",
    companyLogo: companyLogos.abb,
    location: "Cairo, Egypt",
    workType: "Hybrid",
    isViewed: true,
    postedAt: "1 week ago",
  },
  {
    id: 2,
    title: "Senior Product Designer",
    company: "Sony",
    companyLogo: companyLogos.sony,
    location: "Cairo, Egypt",
    workType: "Hybrid",
    isViewed: true,
    mutualConnectionsCount: 2,
    postedAt: "1 week ago",
  },
  {
    id: 3,
    title: "Senior Product Designer",
    company: "Sony",
    companyLogo: companyLogos.sony,
    location: "Cairo, Egypt",
    workType: "Hybrid",
    isViewed: true,
    mutualConnectionsCount: 2,
    postedAt: "1 week ago",
  },
  {
    id: 4,
    title: "Senior Product Designer",
    company: "LG",
    companyLogo: companyLogos.lg,
    location: "Cairo, Egypt",
    workType: "Hybrid",
    isViewed: false,
    postedAt: "1 week ago",
  },
  {
    id: 9,
    title: "UI/UX Designer",
    company: "ABB",
    companyLogo: companyLogos.abb,
    location: "Cairo, Egypt",
    workType: "Remote",
    isViewed: false,
    postedAt: "3 days ago",
  },
  {
    id: 10,
    title: "Product Design Lead",
    company: "Phillips",
    companyLogo: companyLogos.phillips,
    location: "Cairo, Egypt",
    workType: "Onsite",
    isViewed: true,
    mutualConnectionsCount: 1,
    postedAt: "4 days ago",
  },
  {
    id: 11,
    title: "Senior Product Designer",
    company: "Samsung",
    companyLogo: companyLogos.samsung,
    location: "Cairo, Egypt",
    workType: "Hybrid",
    isViewed: false,
    postedAt: "5 days ago",
  },
  {
    id: 12,
    title: "UX Researcher",
    company: "Nokia",
    companyLogo: companyLogos.nokia,
    location: "Cairo, Egypt",
    workType: "Remote",
    isViewed: true,
    mutualConnectionsCount: 3,
    postedAt: "6 days ago",
  },
];

export const recommendedJobs: Job[] = [
  {
    id: 5,
    title: "Senior Product Designer",
    company: "Phillips",
    companyLogo: companyLogos.phillips,
    location: "Cairo, Egypt",
    workType: "Hybrid",
    isViewed: true,
    postedAt: "1 week ago",
  },
  {
    id: 6,
    title: "Senior Product Designer",
    company: "HP",
    companyLogo: companyLogos.hp,
    location: "Cairo, Egypt",
    workType: "Hybrid",
    isViewed: true,
    mutualConnectionsCount: 2,
    postedAt: "1 week ago",
  },
  {
    id: 7,
    title: "Senior Product Designer",
    company: "Samsung",
    companyLogo: companyLogos.samsung,
    location: "Cairo, Egypt",
    workType: "Hybrid",
    isViewed: false,
    postedAt: "1 week ago",
  },
  {
    id: 8,
    title: "Senior Product Designer",
    company: "Nokia",
    companyLogo: companyLogos.nokia,
    location: "Cairo, Egypt",
    workType: "Hybrid",
    isViewed: false,
    mutualConnectionsCount: 1,
    postedAt: "1 week ago",
  },
  {
    id: 13,
    title: "Product Designer",
    company: "HP",
    companyLogo: companyLogos.hp,
    location: "Cairo, Egypt",
    workType: "Onsite",
    isViewed: false,
    postedAt: "2 days ago",
  },
  {
    id: 14,
    title: "Junior Product Designer",
    company: "LG",
    companyLogo: companyLogos.lg,
    location: "Cairo, Egypt",
    workType: "Hybrid",
    isViewed: true,
    mutualConnectionsCount: 1,
    postedAt: "3 days ago",
  },
  {
    id: 15,
    title: "Design Systems Specialist",
    company: "Sony",
    companyLogo: companyLogos.sony,
    location: "Cairo, Egypt",
    workType: "Remote",
    isViewed: false,
    postedAt: "5 days ago",
  },
  {
    id: 16,
    title: "Senior Product Designer",
    company: "ABB",
    companyLogo: companyLogos.abb,
    location: "Cairo, Egypt",
    workType: "Onsite",
    isViewed: true,
    mutualConnectionsCount: 4,
    postedAt: "1 week ago",
  },
];
